default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: twogetr_development

test:
  <<: *default
  database: twogetr_test

production:
  <<: *default
  database: twogetr_production
  username: railsrox
  password: <%= ENV['DATABASE_PASSWORD'] %>
